### ISSUE TITLE
Why override __setitem__ in PMark?

### ISSUE THREAD

**Issue by smiszym** [ParrotPrediction/pyalcs#19]
The line `self[idx] = perception[idx]` would look far more understandable if written as `self[idx].add(perception[idx])` - it would be clear that `self[idx]` is a set and we add a new value to it, instead of replacing `idx`-th item of `self` altogether.

https://github.com/ParrotPrediction/pyalcs/blob/547ae0d4907939f69713d1fe0883929815c7816c/alcs/acs2/PMark.py#L33-L36

I suggest removing `__setitem__` override and simply using `self[idx].add(perception[idx])` when needed instead of `self[idx] = perception[idx]`

**Comment by khozzy** [comment]
You're right. But I need to dig into the code to see why I did so.

**Comment by khozzy** [comment]
Fixed
